# Generated by Django 2.2.5 on 2019-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('delivery_date', models.DateField(blank=True)),
                ('product_id', models.TextField()),
                ('amount', models.IntegerField()),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
    ]
